# Generated by Django 5.2 on 2025-05-03 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='item',
            name='min_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='item',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad en inventario'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Mantenimiento', 'Mantenimiento'), ('No disponible', 'No disponible'), ('Bajo stock', 'Bajo stock'), ('Agotado', 'Agotado')], default='Disponible', max_length=100),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('old_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('user', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
